apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetrack-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: kubetrack.local  # /etc/hosts === ( 127.0.0.1    kubetrack.local )

      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubetrack-service
                port:
                  number: 80

