apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngo
  template:
    metadata:
      labels:
        app: ngo
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-track
      containers:
      - name: ngo
        image: pro1116/ngo:${IMAGE_TAG}  # Replace dynamically in Jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: IMAGE_TAG
          value: "${IMAGE_TAG}"  # Optional: expose to container as an env var

---

apiVersion: v1
kind: Service
metadata:
  name: ngo-service
spec:
  selector:
    app: ngo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002

