apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetrack-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetrack
  template:
    metadata:
      labels:
        app: kubetrack
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-track
      containers:
      - name: kubetrack
        image: pro1116/kubetrack:${IMAGE_TAG}  # Dynamic image tag to be replaced in Jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: IMAGE_TAG
          value: "${IMAGE_TAG}"  # Optional: also pass it inside the container as env var

---

apiVersion: v1
kind: Service
metadata:
  name: kubetrack-service
spec:
  selector:
    app: kubetrack
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001

